### ISSUE TITLE
[Suggestion]/[Feature Request]

### ISSUE THREAD

**Issue by NarasimaPandiyan** [Clickism/ClickVillagers#1]
For the past two days, I've been experimenting with the plugin. One idea I'd like to explore is incorporating **zombie villagers** into it, or enabling the ability to place a villager in a minecart using shift right-click. So that they won't run away while getting their brains eaten.

**Comment by Clickism** [comment]
Wow those are some really good suggestions! I'm currently working on an update to fix some bugs/optimize. But after that I'll work on a feature update and will definitely add your suggestions into the plugin :)

**Comment by NarasimaPandiyan** [comment]
can't wait to integrate this into my zombification chamber. lol . for now I will use a pit to the job done 🤣

**Comment by NarasimaPandiyan** [comment]
Well, thanks for plugin buddy 🤗

**Comment by Clickism** [comment]
Hey! I published a new update and added your suggestions. I credited you as well: https://modrinth.com/plugin/clickvillagers

**Comment by NarasimaPandiyan** [comment]
> Hey! I published a new update and added your suggestions. I credited you as well: https://modrinth.com/plugin/clickvillagers

We've just added the new version on our server and we're really enjoying it 😍. Many thanks for the update, my friend!!

**Comment by Clickism** [comment]
🥰 I'm really happy to hear that! Thanks for the suggestions again :)
