### ISSUE TITLE
Villager data gone

### ISSUE THREAD

**Issue by RadyReady** [Clickism/ClickVillagers#16]
i put this plugin in my friend server and first off it was normal but then when i try to put my villager back on to the overworld theres a message saying their data its gone so is there a fix?

**Comment by Ucda1212** [comment]
Also receiving the same error. Seems to happen when someone kills @e[type=villager]

**Comment by Clickism** [comment]
Yes, killing all villagers would wipe out the data. I will keep in mind to add in a future version, that picked up villagers can't be /kill'd.

**Comment by Clickism** [comment]
Fixed in version 0.5
