### ISSUE TITLE
Request : Lands integration

### ISSUE THREAD

**Issue by Bulgus** [Clickism/ClickVillagers#17]
I need land integration, or at least worldguard, for my server. Anyone can take villagers anywhere in any claim... no need to explain the problem ^^.

Is integration with the [Lands](https://www.spigotmc.org/resources/lands-%E2%AD%95-land-claim-plugin-%E2%9C%85-grief-prevention-protection-gui-management-nations-wars-1-20-support.53313/) faction plugin possible?

**Comment by Bulgus** [comment]
#14 Implemented here

**Comment by Clickism** [comment]
Fixed in version 0.5
