### ISSUE TITLE
Issue with Villager Hoppers

### ISSUE THREAD

**Issue by iDutch** [Clickism/ClickVillagers#2]
Discovered this plugin yesterday and been playing around with it for a bit. 
I found an issue where if you break a Villager Hopper that contains villagers, the villagers are gone/voided.

**Comment by Clickism** [comment]
Thanks for reporting the bug, I fixed the bug and updated a new version on spigot, you can download it there: https://www.spigotmc.org/resources/clickvillagers.111424/

**Comment by Katables** [comment]
This is not fixed as of 1.21.4 
Click Villagers Version 1.2.2
