### ISSUE TITLE
Villagers Disappear after Placement

### ISSUE THREAD

**Issue by ChubbyWubbby** [Clickism/ClickVillagers#21]
When I pick up the villager it goes into my inventory just fine. However, when I place it down the villager head will go onto the block I placed it on for a split second but then the villager turns invisable. The villager makes its "huh" noise but is unable to be seen. When I leave the area and come back the villagers magically show up. I am also running a minecraft server with 1.21 so I am not sure if that is why this is an issue. 

Thanks,

**Comment by Lsuyse** [comment]
Yes, we have the same problem, after we take the villagers and put them in, they become invisible, to make them reappear, put a bed somewhere in the evening, if they sleep, they become visible.

I hope they will fix it.

**Comment by Clickism** [comment]
Fixed in version 0.5
