### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Giltory** [Clickism/ClickVillagers#24]
Love the plugin but when people pick up villagers and never put them back down, it puts the villagers in the void below spawn. I average like 20-30 people on the server at a time so these villagers built up and started causing lag. There were around 500 villagers below spawn which was causing TPS issues. I'm not sure if there is a way to change how you store villager entities but I'd really like to continue using the plugin but I currently am not with all the lag. 

![villager](https://github.com/user-attachments/assets/b47fe8a3-2822-4c38-b64b-ce1a536c8153)

**Comment by Clickism** [comment]
I will keep performance improvements in mind if I rewrite the plugin in the future.

**Comment by Clickism** [comment]
Update on this, the storage logic in the rewrite is completely different now. The NBT data of the villager is now written directly onto the head item via NMS and the villager is removed from the world. So the villagers no longer get sent under bedrock, but are removed entirely when picked up and come with zero server performance hit.
