### ISSUE TITLE
Not Being Able To Join Server With This Mod

### ISSUE THREAD

**Issue by ammaar2436** [Clickism/ClickVillagers#25]
So I recently started a new purpur server to play with my friends and I added this mod, it wouldn't let me nor my friends to be able to join the server. Its a purpur server 1.21 with other mods, when i remove this mod im able to join the server. Pls let me know how I can fix this issue.
![image](https://github.com/user-attachments/assets/8f3e41a4-9b1c-4fbe-bf1a-bd57602905e3)
This os the error im getting, and the server is cracked for tlauncher players.

**Comment by Palxz** [comment]
Same thing happening on my end, found a temporary solution is to just disable the Villager Hopper in the "config.yml" of your server.
The issue seems to be revolving in the recipe of the hopper, i have no idea what but it lies there.

**Comment by scottoffen** [comment]
I can confirm, I had the same issue, and disabling the Villager Hopper in the config.yml file fixed my issue.

**Comment by Clickism** [comment]
Should be fixed in version 0.5.1.
Download on spigot: https://www.spigotmc.org/resources/clickvillagers.111424/

**Comment by scottoffen** [comment]
I can confirm that this is working for me now using [Purpur 1.20.6 build 2233](https://purpurmc.org/downloads/1.20.6)

**Comment by Clickism** [comment]
Great!
