### ISSUE TITLE
1.21.1>?

### ISSUE THREAD

**Issue by aysaoif** [Clickism/ClickVillagers#26]
implement  it faster please!

**Comment by Clickism** [comment]
Does the plugin not work on 1.12.1? Have you tried running it? If so, could you send the log messages if there is an error?

**Comment by aysaoif** [comment]
> Does the plugin not work on 1.21.1? Have you tried running it? If so, could you send the log messages if there is an error?

errors: https://github.com/Clickism/ClickVillagers/issues/25

**Comment by Clickism** [comment]
Should be fixed in version 0.5.1.
Download on spigot: https://www.spigotmc.org/resources/clickvillagers.111424/
