### ISSUE TITLE
Request: WorldGuard Integration

### ISSUE THREAD

**Issue by LandOfPeeps** [Clickism/ClickVillagers#7]
Is it possible to add a WorldGuard flag to disable and enable people to kidnap the villagers, players are able to steal villager NPCs from hubs and stuff due to this

**Comment by Clickism** [comment]
You can use claims to protect villagers.

**Comment by LandOfPeeps** [comment]
This doesnt work with some npc villagers that open a custom GUI after the claim GUI opens such as villagers from VillagerMarket so a /claim command would be a nice workaround
