### ISSUE TITLE
Villager hopper incompatibility with hoppersorter

### ISSUE THREAD

**Issue by Razorxd1993** [Clickism/ClickVillagers#8]
the Villager Hopper creates an incompatibility with the HopperSorter plugin.
If you deactivate the Villager hopper, you can no longer place a HopperSorter and if you activate this function, place a HopperSorter and remove it again, the Armorstand with the emerald edge of the Villagerhopper remains.

It would be cool if the function can be completely disabled directly, so that the Villagerhopper does not interfere with the functions of the HopperSorter.

Link: HopperSorter
https://www.spigotmc.org/resources/hoppersorter-1-8-1-20-1-upgradable-item-filter-transfer-item-smelt-multiple-block-linking.80528/

**Comment by Clickism** [comment]
The plugin you mentioned is unfortunately not open source, therefore I can't diagnose the exact problem. I could hypothetically change the hopper item in a future update to avoid conflicts but that would break previously crafted villager hoppers.
